# Package/project name. Used internally by Flutter and for publishing.
name: quber_taxi

# A brief description of the project.
description: "A new Flutter project."

# Indicates this package will NOT be published to pub.dev (official package repository).
publish_to: 'none'

# App version: 1.4.0 is the semantic version.
# Flutter uses this to set versionName and versionCode on Android, and version on iOS.
version: 1.5.0

# Defines the minimum Dart SDK version supported by this app.
environment:
  sdk: ^3.6.1

# External dependencies used by the app.
dependencies:
  flutter:
    sdk: flutter  # Core Flutter framework (required).

  # Mapbox SDK for Flutter.
  mapbox_maps_flutter: 2.8.0

  # Access to device geolocation.
  geolocator: 13.0.2

  #App Splash
  flutter_native_splash: ^2.4.6

  # Geospatial calculation.
  turf: ^0.0.10

  # HTTP client for web requests.
  http: ^1.4.0

  # Utilities for parsing HTTP content.
  http_parser: ^4.0.2

  # MIME type detection for files.
  mime: ^1.0.4

  # Package info for getting app version
  package_info_plus: ^8.0.2

  # Custom business logic from a Git repository.
  flutter_fusion:
    git:
      url: https://github.com/yapmDev/flutter-fusion.git

  # Network connectivity checker (Git repository).
  network_checker:
    git:
      url: https://github.com/yapmDev/network-checker.git

  # Use Google Fonts in the app.
  google_fonts: ^6.2.1

  # WebSocket client for real-time messaging.
  stomp_dart_client: ^2.1.3

  # SVG image rendering.
  flutter_svg: ^2.1.0

  # Routing and navigation management.
  go_router: ^15.1.3

  # Internationalization and localization utilities.
  intl: ^0.20.2

  # Official Flutter package for localization support.
  flutter_localizations:
    sdk: flutter

  # Launch external URLs (browser, email, phone).
  url_launcher: ^6.3.1

  # Simple local key-value storage.
  shared_preferences: 2.5.3

  # Google ML Kit face detection.
  google_mlkit_face_detection: ^0.11.1

  # Camera access and control.
  camera: ^0.10.5+2

  # Permission handling for iOS and Android.
  permission_handler: ^11.3.1

  # Image and video picker from gallery or camera.
  image_picker: ^1.1.2

  # Advanced image manipulation library.
  image: ^4.0.17

  path_provider: ^2.1.2
  path: ^1.9.0
  crypto: ^3.0.3

  curved_navigation_bar: ^1.0.6
  sentry_flutter: ^9.5.0

  #preview app to test responsiveness
  device_preview: ^1.3.1

# Development dependencies for testing and code generation.
dev_dependencies:
  # Official Flutter testing framework.
  flutter_test:
    sdk: flutter

  # Linting rules for good code style.
  flutter_lints: ^5.0.0

  # Tool for automatic code generation.
  build_runner: ^2.5.4

  #Util tool for flavors
  flutter_flavorizr: ^2.4.1

# Flutter-specific configuration.
flutter:
  # Enables automatic code generation for assets and localization.
  generate: true

  # Indicates use of Material Design widgets and themes.
  uses-material-design: true

  # List of asset directories and files to package inside the app.
  assets:
    - assets/geojson/polygon/
    - assets/geojson/line/
    - assets/geojson/suggestions.json
    - assets/icons/discounts/x24/
    - assets/icons/discounts/x48/
    - assets/icons/discounts/x72/
    - assets/icons/
    - assets/images/vehicles/mdpi/
    - assets/images/vehicles/hdpi/
    - assets/images/vehicles/xhdpi/
    - assets/images/
    - assets/markers/route/x60/
    - assets/markers/route/x120/
    - assets/markers/route/x180/
    - assets/markers/taxi/
    - assets/launch/

# Configuration for the flutter_intl plugin for localization.
flutter_intl:
  # Enables support for translations and language management.
  enabled: true

flutter_native_splash:
  color: "#fbb635"
  color_dark: "#151515"
  image: assets/launch/splash_client.png
  image_dark: assets/launch/icon_app_flutter_dark.png
  android: true
  ios: false
  web: true
  android_12:
    image: assets/launch/splash_client.png
    color: "#fbb635"
    icon_background_color: "#fbb635"
    color_dark: "#151515"
    icon_background_color_dark: "#151515"
    image_dark: assets/launch/icon_app_flutter_dark.png

